[ 2025-05-17 00:48:27,484 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.6.39:5000
[ 2025-05-17 00:48:27,484 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-05-17 00:48:35,641 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path = os.path.join("artifacts", "model.pkl")
                 ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\app.py", line 43, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2025-05-17 00:48:35,646 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/May/2025 00:48:35] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-05-17 00:48:42,705 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path = os.path.join("artifacts", "model.pkl")
                 ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\anaconda3\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\app.py", line 43, in predict_datapoint
    results = predict_pipeline.predict(pred_df)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [C:\Users\91999\OneDrive\Desktop\MLProjects\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2025-05-17 00:48:42,708 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/May/2025 00:48:42] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-05-17 00:48:47,394 ] 97 werkzeug - INFO - 127.0.0.1 - - [17/May/2025 00:48:47] "[33mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 404 -
